version: '3.9'

services:
  nginx:
    build: ./nginx
    ports:
     - "80:80"
    restart: always
    depends_on:
     - web1
     - web2

  redis:
    image: redis:alpine
    volumes:
     - redis-data:/data
    restart: always
    ports:
     - "6379:6379"

  web1:
    build: ./web01
    ports:
     - "81:5000"
    restart: always
    depends_on: 
     - redis

  web2:
    build: ./web02
    ports:
     - "82:5000"
    restart: always
    depends_on:
     - redis

volumes:
  redis-data:
    driver: local 
